---
- name: Bring down Docker Compose and remove volumes
  ansible.builtin.command:
    cmd: docker-compose down -v
    chdir: /home/{{ ansible_user }}/{{ github_repo_name }}/Inception

- name: Removed unused Docker volumes
  ansible.builtin.command:
    cmd: docker volume prune -f