FROM debian:buster

RUN apt-get update && apt-get install -y --no-install-recommends \
  nginx \
  openssl \
  && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./conf/nginx.conf /etc/nginx/sites-available/wordpress

RUN rm /etc/nginx/sites-enabled/default && \
  ln -s /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/wordpress

RUN mkdir -p /etc/nginx/ssl \
  && openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout /etc/nginx/ssl/{{ domain_name }}.key -out /etc/nginx/ssl/{{ domain_name }}.crt \
  -subj "/C=MY/ST=Selangor/L=Kuala Lumpur/O=42KL/OU={{ ansible_user }}/CN={{ domain_name }}"

ENTRYPOINT [ "/entrypoint.sh" ]

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
