---
- name: Check if project directory exists
  ansible.builtin.stat:
    path: /home/{{ ansible_user }}/project
  register: project_dir

- name: Create project directory on managed node if not exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/project
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  when: not project_dir.stat.exists

- name: Check if docker-compose.yml exists
  ansible.builtin.stat:
    path: /home/{{ ansible_user }}/project/docker-compose.yml
  register: docker_compose_file

- name: Copy docker-compose file to managed node
  ansible.builtin.copy:
    src: ../Inception/docker-compose.yml
    dest: /home/{{ ansible_user }}/project/docker-compose.yml
    mode: '0644'
  when: not docker_compose_file.stat.exists

- name: Report on docker-compose.yml presence
  ansible.builtin.debug:
    msg: "File exists"
  when: docker_compose_file.stat.exists
