services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - frontend
    volumes:
      - wordpress_website:/var/www/html
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env.wp
    networks:
      - frontend
      - backend
    volumes:
      - wordpress_website:/var/www/html
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env.db
    networks:
      - backend
    volumes:
      - wordpress_database:/var/lib/mysql
    restart: unless-stopped

  pma:
    build: ./requirements/phpmyadmin/
    env_file:
      - .env.pma
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: unless-stopped


networks:
  frontend:
  backend:


volumes:
  wordpress_website:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/wxuerui/data/wordpress_website'

  wordpress_database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/wxuerui/data/wordpress_database'

